# Generated by Django 5.0.6 on 2024-05-21 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fotoslivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('link', models.URLField(verbose_name='Image URL')),
            ],
        ),
        migrations.CreateModel(
            name='usuariosCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de email')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('cpf', models.CharField(max_length=20)),
                ('biografia', models.CharField(max_length=200)),
                ('cargo', models.CharField(choices=[('A', 'ADM'), ('AU', 'AUTOR'), ('B', 'BIBLIOTECARIO(a)'), ('U', 'USUARIO')], default='U', max_length=100)),
                ('foto', models.URLField(verbose_name='Image URL')),
            ],
        ),
        migrations.CreateModel(
            name='livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('numero_pagina', models.IntegerField()),
                ('formato', models.CharField(choices=[('E', 'E-BOOK'), ('F', 'FISICO')], max_length=100)),
                ('numero_edicao', models.IntegerField()),
                ('publicacao', models.IntegerField()),
                ('status', models.CharField(choices=[('E', 'E-BOOK'), ('F', 'FISICO')], default='P', max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoriaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriasFKFK', to='app.categorias')),
                ('imagemfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotosusuariosFKFK', to='app.fotoslivro')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotosusuariosFKFK', to='app.usuarioscustomizado')),
            ],
        ),
        migrations.CreateModel(
            name='emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('livroFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.livro')),
                ('usuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='app.usuarioscustomizado')),
            ],
        ),
    ]
