# Generated by Django 5.0.6 on 2024-05-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioscustomizado',
            name='nome',
        ),
    ]
