# Generated by Django 5.0.6 on 2024-05-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrinho_pecas_produto_pagamento_pedidos_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereço',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
    ]
