# Generated by Django 5.0.6 on 2024-05-19 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='subprodutoFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_produto', to='app.sub_produto'),
        ),
    ]
