# Generated by Django 5.0.6 on 2024-05-19 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_produto_subprodutofk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='subprodutoFK',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sub_produto'),
        ),
    ]
