# Generated by Django 5.0.6 on 2024-05-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_produto_subprodutofk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='subprodutoFK',
        ),
        migrations.DeleteModel(
            name='sub_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='subprodutoFK',
            field=models.ManyToManyField(to='app.pecas'),
        ),
    ]
