# Generated by Django 5.0.6 on 2024-05-21 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_carrinho_produtofk_carrinho_produtofk'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fotoslivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('link', models.URLField(verbose_name='Image URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='valor_carrinho',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='produtoFK',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='status',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='subprodutoFK',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.CreateModel(
            name='livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('numero_pagina', models.IntegerField()),
                ('formato', models.CharField(choices=[('E', 'E-BOOK'), ('F', 'FISICO')], max_length=100)),
                ('numero_edicao', models.IntegerField()),
                ('publicacao', models.IntegerField()),
                ('status', models.CharField(choices=[('E', 'E-BOOK'), ('F', 'FISICO')], default='P', max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotosusuariosFKFK', to=settings.AUTH_USER_MODEL)),
                ('categoriaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriasFKFK', to='app.categorias')),
                ('imagemfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotosusuariosFKFK', to='app.fotoslivro')),
            ],
        ),
        migrations.CreateModel(
            name='emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('usuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
                ('livroFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.livro')),
            ],
        ),
        migrations.DeleteModel(
            name='carrinho',
        ),
        migrations.DeleteModel(
            name='imagem',
        ),
        migrations.DeleteModel(
            name='pagamento',
        ),
        migrations.DeleteModel(
            name='pedidos',
        ),
        migrations.DeleteModel(
            name='pecas',
        ),
        migrations.DeleteModel(
            name='produto',
        ),
    ]
