# Generated by Django 5.0.6 on 2024-05-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='livroFK',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livroFK',
            field=models.ManyToManyField(to='app.livro'),
        ),
    ]
