# Generated by Django 5.0.6 on 2024-05-22 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_emprestimo_livrofk_alter_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoslivro',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='imagemfk',
        ),
        migrations.AddField(
            model_name='fotoslivro',
            name='livroFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livroFKFK', to='app.livro'),
        ),
    ]
