# Generated by Django 5.0.6 on 2024-05-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_fotoslivro_nome_remove_livro_imagemfk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoslivro',
            name='livroFK',
        ),
        migrations.AddField(
            model_name='fotoslivro',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='fotosFK',
            field=models.ManyToManyField(to='app.fotoslivro'),
        ),
    ]
