# Generated by Django 5.0.6 on 2024-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_fotoslivro_livrofk_fotoslivro_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
