# Generated by Django 5.0.6 on 2024-05-26 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_livro_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado(a)'), ('A', 'Aprovado(a)')], default='U', max_length=100),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuariosFKFK', to=settings.AUTH_USER_MODEL),
        ),
    ]
