# Generated by Django 5.0.6 on 2024-05-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_usuario_cargo_alter_livro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('A', 'ADMIN'), ('B', 'BIBLIOTECARIO(A)'), ('AU', 'AUTOR(A)'), ('U', 'USUARIO(A)')], default='U', max_length=100),
        ),
    ]
