# Generated by Django 5.0.6 on 2024-05-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_emprestimo_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
