# Generated by Django 5.0.6 on 2024-05-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_emprestimo_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='formato',
            field=models.CharField(choices=[('E-BOOK', 'E-BOOK'), ('FISICO', 'FISICO')], max_length=100),
        ),
    ]
